[tool.poetry]
name = "scalper-project"
version = "0.1.0"
description = ""
authors = ["TAYLOR JOHNSON <TAYLOR.MCMINN@GMAIL.COM>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^2.1.3"
pandas = "^1.0.3"
matplotlib = "^3.2.1"
numpy = "^1.18.4"
sklearn = "^0.0"
seaborn = "^0.10.1"
statsmodels = "^0.11.1"

scipy = "^1.5.4"

matplotlib = "^3.3.3"
numpy = "^1.19.4"
sklearn = "^0.0"
statsmodels = "^0.12.1"
black = "^20.8b1"


[tool.poetry.dev-dependencies]
<<<<<<< HEAD
pylint = "^2.6.0"
=======
black = {version = "^20.8b1", allow-prereleases = true}
>>>>>>> bfc1cd90aa76421b7c687b1cd9cc984af9bd762b

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
